### PR TITLE
updated host url in production.rb from defcon-firehose to firehose-de…

### PR DESCRIPTION
**Pull request by NKHolton**
Updated mailer host url from the incorrect 'defcon-firehose.herokuapp.com' to the correct 'firehose-defcon.herokuapp.com' so it matches the production host url.

### CODE REVIEW

**Comment by NKHolton** [comment]
Interested to see what check failed?  Just realized I didn't do 'git pull origin master' before my update and pull request so don't know if that has an effect?

**Comment by kenmazaika** [comment]
Your code looks good to me.  There might be a problem with CodeShip.  CodeShip should only fail if the test suite fails.  Can you run the following command:

```
bundle exec rake
```

And report the output?  If all the tests pass, it's not a problem with the code, but rather a problem with CodeShip (it's a service that automatically runs the tests).

**Comment by NKHolton** [comment]
Hey Ken, the output was:

_Web Console is activated in the test environment, which is
usually a mistake. To ensure it's only activated in development
mode, move it to the development group of your Gemfile:

```
gem 'web-console', group: :development
```

If you still want to run it the test environment (and know
what you are doing), put this in your Rails application
configuration:

```
config.web_console.development_only = false_
```

**Comment by kenmazaika** [comment]
Odd.  This looks like it caused some problems.  Likely by upgrading a few of the gems. @robertsapunarich can you work with Natalie to resolve the problem?

**Comment by NKHolton** [comment]
Not sure if it's related to this error I keep getting when trying to start the server that tells me something about the native extension 'unf_ext -v '0.0.7.1' and g++.  Robert actually was helping me and I ran 'sudo apt-get install g++' which helped the other day but ran into the same error yesterday.  After running bundle update yesterday the server seemed to work fine after that.  Robert and I are trying to figure out our schedules to connect and may not until tomorrow.  Any suggestions, Ken?  My worry was putting 'gem unf_ext 0.0.7.1' in the gem file doing an install then screwing something up for the group.

**Comment by kenmazaika** [comment]
You seem to have upgraded the `web-console` gem and you are now seeing errors about `web-console`.  I'd suggest changing the version back to the old one.  I.e. only make changes to `production.rb`, do not make any changes to the `Gemfile.lock`.

Rather than running `bundle update` do `bundle install`.  I'd branch off of the master branch and re-do the change to `production.rb`.

**Comment by NKHolton** [comment]
So did bundle update change something in Gemfile.lock because so far I have put nothing new in there myself.  I tried bundle install yesterday but that still gave me the issue of unf-ext.  So do I need to do anything before creating another new branch and trying to edit production.rb again?  Thanks!

**Comment by kenmazaika** [comment]
Make sure to make the branch off master.

```
git checkout master
```

```
git branch new-branch-name
```

**Comment by NKHolton** [comment]
Ok, I did that before but just went back in and made sure it was on master branch.  Then I did 'git branch update-mailer-host-to-match-production-host', then git checkout 'update-mailer-host-to-match-production-host'.  After entering it says 'M     Gemfile.lock'....'switched to branch 'update-mailer-host-to-match-production-host'.  Am I doing something wrong?

**Comment by kenmazaika** [comment]
It sounds like you're bringing modifications to the `Gemfile.lock` with you.  Why don't you take a look at this issue on your next mentor session?

**Comment by NKHolton** [comment]
Sounds good.

**Pull request closed without merging**
