### PR TITLE
email users when post is created

### PR DESCRIPTION
**Pull request by ceceliahavens**
Since we have Mailgun already in place, I added a NotificationMailer and two email views 
When I try to test the email delivery system I get the error

NoMethodError: undefined method `user' for nil:NilClass

I cleared out the post database and created new posts to see if that solved the error of not recognizing users that were created before this NotificationMailer, but I get the same errors.  Do I need to create a new user to test this?  At this point I believe I have over read on the matter and all options are blurring together. 

I have looked over all the stackO, posts, read the mailgun documentation the ActionMailer documentation, looked at hundred of ruby github mailer codes to see what other developers do and I'm still having trouble getting it to work correctly.   Could someone please look it over and help me out? Thanks

### CODE REVIEW

**Comment by kenmazaika** [comment]
What you have so far looks good.  Why don't you include the code that is producing the errors as well.

**Comment by ceceliahavens** [comment]
2.2.1 :001 > NotificationMailer.send_notification(user).deliver
NameError: undefined local variable or method `user' for main:Object
        from (irb):1
        from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.0.1/lib/rails/commands/console.rb:90:in`start'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.0.1/lib/rails/commands/console.rb:9:in `start'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.0.1/lib/rails/commands.rb:62:in`<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in`<main>'
2.2.1 :002 >

**Comment by kenmazaika** [comment]
That indicates you don't have the `user` variable set in the console.

```
user = User.first
```

Should set that to something.

**Comment by ceceliahavens** [comment]
(I'm not sure what happened,  but I posted this last night and it appears to have disappeared?) reposted this morning. 

--Sorry, I spaced out and forgot to set the variable in my last post, but I have been doing it consistently as I went along trying to test out the email.   Until these last few tweaks to the code I have been consistently getting a NoMethod Error, but this missing template error pasted below is new

2.2.1 :001 > user = User.first
  User Load (0.7ms)  SELECT "users".\* FROM "users" ORDER BY "users"."id" ASC LIMIT 1
 => #<User id: 1, email: "ceceliahavens@hotmail.com", encrypted_password: "$2a$10$ITe04FwTntAWCIoS6c7juuXTPL40zy6ONNOB4phPDuq9...", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 18, current_sign_in_at: "2016-01-05 17:09:45", last_sign_in_at: "2016-01-01 23:09:05", current_sign_in_ip: #<IPAddr: IPv4:68.143.13.150/255.255.255.255>, last_sign_in_ip: #<IPAddr: IPv4:70.129.190.202/255.255.255.255>, created_at: "2015-12-14 00:52:06", updated_at: "2016-01-05 17:09:45", admin: false, post_notification: true, comment_notification: true, name: "I Am Awesome">
2.2.1 :002 > NotificationMailer.send_notification(user).deliver
   (0.4ms)  SELECT "users"."email" FROM "users"
ActionView::MissingTemplate: Missing template notification_mailer/send_notification with "mailer". Searched in:
- "notification_mailer"
  
  ```
  from /usr/local/rvm/gems/ruby-2.2.1/gems/actionmailer-4.0.1/lib/action_mailer/base.rb:767:in `each_template'
  from /usr/local/rvm/gems/ruby-2.2.1/gems/actionmailer-4.0.1/lib/action_mailer/base.rb:751:in `collect_responses'
  from /usr/local/rvm/gems/ruby-2.2.1/gems/actionmailer-4.0.1/lib/action_mailer/base.rb:691:in `mail'
  from /home/ubuntu/workspace/DEFCON/app/mailers/notification_mailer.rb:7:in `send_notification'
  from /usr/local/rvm/gems/ruby-2.2.1/gems/actionpack-4.0.1/lib/abstract_controller/base.rb:189:in `process_action'
  from /usr/local/rvm/gems/ruby-2.2.1/gems/actionpack-4.0.1/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.0.1/lib/active_support/callbacks.rb:373:in `_run__433199227953446992__process_action__callbacks'
  from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.0.1/lib/active_support/callbacks.rb:80:in `run_callbacks'
  from /usr/local/rvm/gems/ruby-2.2.1/gems/actionpack-4.0.1/lib/abstract_controller/callbacks.rb:17:in `process_action'
  from /usr/local/rvm/gems/ruby-2.2.1/gems/actionpack-4.0.1/lib/abstract_controller/base.rb:136:in `process'
  from /usr/local/rvm/gems/ruby-2.2.1/gems/actionpack-4.0.1/lib/abstract_controller/rendering.rb:44:in `process'
  from /usr/local/rvm/gems/ruby-2.2.1/gems/actionmailer-4.0.1/lib/action_mailer/base.rb:503:in `process'
  from /usr/local/rvm/gems/ruby-2.2.1/gems/actionmailer-4.0.1/lib/action_mailer/base.rb:497:in `initialize'
  from /usr/local/rvm/gems/ruby-2.2.1/gems/actionmailer-4.0.1/lib/action_mailer/base.rb:480:in `new'
  from /usr/local/rvm/gems/ruby-2.2.1/gems/actionmailer-4.0.1/lib/action_mailer/base.rb:480:in `method_missing'
  from (irb):2
  from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.0.1/lib/rails/commands/console.rb:90:in `start'
  from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.0.1/lib/rails/commands/console.rb:9:in `start'
  from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.0.1/lib/rails/commands.rb:62:in `<top (required)>'
  from bin/rails:4:in `require'
  from bin/rails:4:in `<main>'2.2.1 :003 > 
  ```

**Comment by kenmazaika** [comment]
It looks like the name of the view here is:

```
action_notification.html.haml
```

But the name of the mailer action is:

```
send_notification
```

They need to match up.  Also there's a chance (although I doubt it a bit) that mailers don't accept haml and need ERB, but I would check that only if all other checks fail.

**Comment by ceceliahavens** [comment]
Thank you, I didn't realize they had to have the same name. I corrected it, and I still have a few questions:  If you have a standard text.erb file will it be able to pull information from the app like #{@user.email} to personalize the emails when it gets sent?  and when I do the notificationMailer.........deliver action in the console it now says it is sending the email. If I run the tail log it shows it is sending it, but I never receive it.   I do not have access to the application.yml to  verify that setup.  So I went into config/environments/development.rb and changed the config.action_mailer.raise_delivery_errors = false. to true so I could see the error .  I get an error about the ports.(see below)   I didn't set up the Mailgun so I am not certain about the ports chosen, I looked over the mailgun documentation and the first thing I notice is it says to add this authentication/port/domain etc...information in the config/environments/development.rb file but we have it in the production.rb file. since I did not set this up, I am not familiar with the logic or reasoning behind this change, and I don't feel comfortable taking over someone's work without their permission.  Can you advise me on best practices here on both the solving of the mailing problem and making changes to another developers work?  

here is the error: 

Sent mail to ceceliahavens@hotmail.com (68.8ms)
Date: Thu, 07 Jan 2016 20:27:19 +0000
From: noreply@firehose-defcon.com
To: ceceliahavens@hotmail.com
Message-ID: 568eca2766350_a540a6b9905941e@ceceliahavens-basics-2104986.mail
Subject: A new post from ceceliahavens@hotmail.com has been added to the
 Defcon Student Group
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_568eca275e2b0_a540a6b990593d0";
 charset=UTF-8
Content-Transfer-Encoding: 7bit

----==_mimepart_568eca275e2b0_a540a6b990593d0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

Hey There!

#{@user.email}
shared a post with theFirehoseProject Student Group

----==_mimepart_568eca275e2b0_a540a6b990593d0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<p>Hey There!</p>

<p>
  ceceliahavens@hotmail.com
  <b>shared a post with theFirehoseProject Student Group</b>
</p>

----==_mimepart_568eca275e2b0_a540a6b990593d0--

Errno::ECONNREFUSED: Connection refused - connect(2) for "localhost" port 25
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/smtp.rb:541:in `initialize'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/smtp.rb:541:in`open'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/smtp.rb:541:in `tcp_socket'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/smtp.rb:551:in`block in do_start'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:99:in`call'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/smtp.rb:550:in`do_start'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/smtp.rb:520:in `start'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/mail-2.5.4/lib/mail/network/delivery_methods/smtp.rb:112:in`deliver!'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/mail-2.5.4/lib/mail/message.rb:2129:in `do_delivery'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/mail-2.5.4/lib/mail/message.rb:232:in`block in deliver'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/actionmailer-4.0.1/lib/action_mailer/base.rb:456:in `block in deliver_mail'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.0.1/lib/active_support/notifications.rb:159:in`block in instrument'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.0.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.0.1/lib/active_support/notifications.rb:159:in`instrument'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/actionmailer-4.0.1/lib/action_mailer/base.rb:454:in `deliver_mail'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/mail-2.5.4/lib/mail/message.rb:232:in`deliver'
        from (irb):2
        from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.0.1/lib/rails/commands/console.rb:90:in `start'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.0.1/lib/rails/commands/console.rb:9:in`start'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.0.1/lib/rails/commands.rb:62:in `<top (required)>'
        from bin/rails:4:in`require'
        from bin/rails:4:in `<main>'2.2.1 :003 >

**Comment by kenmazaika** [comment]
Hi Cecelia -

Looks like the problem is when it's trying to send the email.  If you add the following to `development.rb` it should just console log the email:

```
ActionMailer::Base.delivery_method = :test
```

**Comment by ceceliahavens** [comment]
I'm a little confused, I've updated the code to reflect this and it is console logging the email, but shouldn't it be sending a real legit email to me as well?  It is hard to see if it is truly working if it isn't truly sending out an email.  What am I missing here your Ken-ness?

**Comment by kenmazaika** [comment]
If you put the mode to `test` it will only add email information to `logs/development.rb`.  If you want to actually preview the email, you'll need to setup the SMTP options and figaro, etc.

You might want to review **[Lesson 41 of Nomster](https://www.thefirehoseproject.com/nomster/41)**.

**Comment by ceceliahavens** [comment]
I have looked several times at the Nomster email steps, and they've been very helpful, I can  see now,  my confusion lies with mailgun....I was under the impression that with mailgun being setup it superseded these steps with Figaro  and smtp, especially since the welcome mailer was already created.  I thought Mailgun was a replacement for this?   Do we want to set this up to actually email out? or do we want to keep it in test mode?

**Comment by kenmazaika** [comment]
Mailgun will only be used on heroku.  It will not be used on localhost. We can keep it in test mode in development, but have it really send emails in production mode.

**Comment by kenmazaika** [comment]
It's related this this issue:

https://github.com/FirehoseCommunity/DEFCON/issues/22

**Comment by ceceliahavens** [comment]
I just added a few changes to the navbar in this branch as well. I think it is ready to be merged if everything checks out.

**Comment by ceceliahavens** [comment]
conflicts resolved ready for a code check and a merge if appropriate. this merge should include both the email capabilities and some fixes for the top navbar.

**Comment by amarkpark** [comment]
@ceceliahavens You may wish to edit the title of the PR to remove the "Do Not Merge" bit... It was only by chance reboot that I saw your comment that this was ready for review/merge :-)

**Comment by kenmazaika** [comment]
New pull requests got merged and there conflicts again.  Sorry @ceceliahavens!

**Comment by ceceliahavens** [comment]
I suspected that would happen since I saw while going through  my emails that @amarkpark  had addressed the navbar as well. I will fix it and get it up and running again.

**Comment by ceceliahavens** [comment]
conflicts resolved ready for review and merge

**Comment by kenmazaika** [comment]
Looks good to me! :+1:

**Pull request merged**
