### PR TITLE
Wireframes.

### PR DESCRIPTION
**Pull request by kenmazaika**
I included the wireframes in the project.  Once these are committed in master, I can add a document that links to the separate pages.

I also added a couple lines to the `.gitignore` in order to ignore OSX systems files.

### CODE REVIEW

**Comment by kenmazaika** [comment]
Also my thought is that this is an invite-only community to start with - so there won't be a "Sign Up" page, but we'll invite people instead.  Removing sign up is a separate feature we can add after we setup the devise in the project.

**Comment by Matt-Lepley** [comment]
Definitely a good starting point, looks great!  

@robertsapunarich what are your thoughts?

**Comment by robertsapunarich** [comment]
@kenmazaika @Matt-Lepley I like it! Maybe add a page that displays an individual user's posts? It's probably a bit much to start off, but it could be a cool feature to consider down the line.

**Comment by Matt-Lepley** [comment]
@robertsapunarich  Definitely a good idea for the user's to have a dashboard. Something we can probably plan out a little further down as you mentioned.

I say thumbs up and ship it! :+1:

**Pull request merged**
