### PR TITLE
Bring comments inside of Post div

### PR DESCRIPTION
**Pull request by jeffgerlach**
Addresses #60. Move comments into bottom of Post div element. Tweak styling to hopefully play nice in mobile. Did notice a few things while testing: 
- Deletes on comments happen immediately. Maybe add a confirmation dialog to avoid mistaken       deletes?
- If you click on the edit button for a comment, you are brought to a standard html form, not the WYSIWYG editor. Same (i think) for post updates.
- If you have a reallllllllly long single word in a post, it will run off outside of the comment blockquote div. Might want to see if we can get that to behave nicely in case of long links, etc. Normal words seem to wrap around fine to the next line.
- Markup using the WYSIWYG editor didn't show up for me in comments. I tried using html_safe but didn't seem to fix it. Should investigate.

Desktop:
screen shot 2016-01-12 at 12 51 17 am

Smaller screen:
screen shot 2016-01-12 at 12 51 43 am

### CODE REVIEW

**Comment by kenmazaika** [comment]
Looks like there are merge conflicts now, otherwise I'd merge it.  Looks good.  As far as this note:

> Markup using the WYSIWYG editor didn't show up for me in comments. I tried using html_safe but didn't seem to fix it. Should investigate.

Should we open a new ticket for this so we don't forget?

**Comment by jeffgerlach** [comment]
Merged with current develop, and ended up throwing in a small bit of javascript to convert the markdown format to HTML to solve #80. Should be good to go!

**Comment by kenmazaika** [comment]
Thumbs up!  Looks good. :+1:

**Comment by kenmazaika** [comment]
I'll make issues for the remaining issues.

**Pull request merged**
