### PR TITLE
HELP ME MR WIZARD - syntax error on test

### PR DESCRIPTION
**Pull request by amarkpark**
I can't figure out why my test is giving me a syntax error in a POST but not a GET.

```
rake aborted!
SyntaxError: /vagrant/src/defcon/test/controllers/votes_controller_test.rb:10: syntax error, unexpected ':', expecting keyword_end
      post :create
            ^
```

Please see votes_controller_test.rb

### CODE REVIEW

**Comment by grandtheft-spaceship** [comment]
Comment

**Comment by amarkpark** [comment]
@kenmazaika After a full reboot I recommitted and pushed with the post :create action active and when CodeShip looked at it and ran rake it failed with the syntax error I was getting locally... Please see build:
https://codeship.com/projects/121383/builds/11405132

If at this point you would like to push up your functioning copy of this feature branch and it doesn't fail I'll be able to verify it is something with my Web Dev Env.

**Comment by kenmazaika** [comment]
This might be an issue with a character that looks like a space but is not one.  I've had problems with that, when copying and pasting code in the past.

Take a look at the branch `kenbranch` - I added the changes I made last night to it.  If that doesn't help we can take a look at it on the call today.

**Comment by kenmazaika** [comment]
Let's re-open this ticket later.

**Pull request closed without merging**
